### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by xorred** [wapiflapi/binglide#6]
Installing on Kali, latest version: 

Traceback (most recent call last):
  File "/usr/local/bin/binglide", line 7, in <module>
    binglide.main()
  File "/usr/local/lib/python3.2/dist-packages/binglide/__init__.py", line 9, in main
    import binglide.gui
  File "/usr/local/lib/python3.2/dist-packages/binglide/gui.py", line 6, in <module>
    from binglide import renderers, levelers, projectors, painters, mixers, calcs
  File "/usr/local/lib/python3.2/dist-packages/binglide/renderers.py", line 67
    yield from cls.get_known(cls.known_levelers, src)
             ^
SyntaxError: invalid syntax

**Comment by wapiflapi** [comment]
This syntax isn't valid in Python 3.2. I use python 3.4. I'm sorry this isn't checked in the `setup.py`. I'll fix this when I have some time.

If python 3.4 is installed or available on kali you can try using that.

Maybe I'll check how much work is required to support python 3.2 for the next version if this is something people actually use.

Thanks for checking out the project!
