### ISSUE TITLE
OpenGL.GL attribute error

### ISSUE THREAD

**Issue by SunnyJames** [wapiflapi/binglide#9]
binglide fails to run for me indicating a module error.  This is on Ubuntu 16.04 with the most recent version of all packages updated.  

>Traceback (most recent call last):
  File "/usr/local/bin/binglide", line 7, in <module>
    binglide.main()
  File "/usr/local/lib/python3.5/dist-packages/binglide/__init__.py", line 9, in main
    import binglide.gui
  File "/usr/local/lib/python3.5/dist-packages/binglide/gui.py", line 6, in <module>
    from binglide import renderers, levelers, projectors, painters, mixers, calcs
  File "/usr/local/lib/python3.5/dist-packages/binglide/renderers.py", line 6, in <module>
    import pyqtgraph.opengl as gl
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/opengl/__init__.py", line 1, in <module>
    from .GLViewWidget import GLViewWidget
  File "/usr/local/lib/python3.5/dist-packages/pyqtgraph/opengl/GLViewWidget.py", line 2, in <module>
    from OpenGL.GL import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 22, in <module>
    formathandler.FormatHandler.loadAll()
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 28, in loadAll
    cls.loadPlugin( entrypoint )
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 430, in <module>
    def mapVBO( vbo, access=GL.GL_READ_WRITE ):
AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'

**Comment by SunnyJames** [comment]
Ok.. this looks like a defect in PyOpenGL which occurs in any import from the OpenGL.GL module. 

I was able to fix it by forcing upgrade of PyOpenGL

`pip3 install --upgrade PyOpenGL`
